# Generated by Django 4.1.2 on 2022-11-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_main_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_badge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.badge'),
        ),
    ]
