# Generated by Django 4.1.2 on 2022-12-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='visit_count',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='stage',
            new_name='requirement',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='userbadge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='user.userbadge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
