# Generated by Django 4.1.2 on 2022-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='radius',
            field=models.FloatField(default=2),
        ),
    ]
