# Generated by Django 4.1.2 on 2022-12-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_visit_count_achievement_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='userbadge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='user.userbadge'),
        ),
    ]
