# Generated by Django 4.1.2 on 2022-12-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_radius'),
        ('user', '0006_alter_achievement_userbadge'),
    ]

    operations = [
    ]
