# Generated by Django 4.1.2 on 2022-10-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(default='', max_length=300)),
                ('weather_degree', models.PositiveSmallIntegerField(default=0)),
                ('wind_degree', models.PositiveSmallIntegerField(default=0)),
                ('happy_degree', models.PositiveSmallIntegerField(default=0)),
                ('humidity_degree', models.PositiveSmallIntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitutde', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
